export const ROUND_TYPES = [
  { value: 'PRE_SEED', label: 'Pre-Seed' },
  { value: 'SEED', label: 'Seed' },
  { value: 'SERIES_A', label: 'Series A' },
  { value: 'SERIES_B', label: 'Series B' },
  { value: 'SERIES_C', label: 'Series C' },
  { value: 'SERIES_D', label: 'Series D' },
  { value: 'SERIES_E', label: 'Series E' },
  { value: 'SERIES_F', label: 'Series F' },
  { value: 'GROWTH', label: 'Growth' },
  { value: 'BRIDGE', label: 'Bridge' },
  { value: 'CONVERTIBLE_NOTE', label: 'Convertible Note' },
  { value: 'DEBT', label: 'Debt' },
  { value: 'GRANT', label: 'Grant' },
  { value: 'UNDISCLOSED', label: 'Undisclosed' },
] as const

export const COUNTRIES = [
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
] as const

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'Washington D.C.' },
] as const

export const CA_PROVINCES = [
  { value: 'AB', label: 'Alberta' },
  { value: 'BC', label: 'British Columbia' },
  { value: 'MB', label: 'Manitoba' },
  { value: 'NB', label: 'New Brunswick' },
  { value: 'NL', label: 'Newfoundland and Labrador' },
  { value: 'NS', label: 'Nova Scotia' },
  { value: 'NT', label: 'Northwest Territories' },
  { value: 'NU', label: 'Nunavut' },
  { value: 'ON', label: 'Ontario' },
  { value: 'PE', label: 'Prince Edward Island' },
  { value: 'QC', label: 'Quebec' },
  { value: 'SK', label: 'Saskatchewan' },
  { value: 'YT', label: 'Yukon' },
] as const

export const INDUSTRIES = [
  { value: 'ai', label: 'AI / Machine Learning' },
  { value: 'biotech', label: 'Biotech / Life Sciences' },
  { value: 'climate', label: 'Climate / Clean Tech' },
  { value: 'consumer', label: 'Consumer' },
  { value: 'crypto', label: 'Crypto / Web3' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'edtech', label: 'EdTech' },
  { value: 'enterprise', label: 'Enterprise Software' },
  { value: 'fintech', label: 'Fintech' },
  { value: 'foodtech', label: 'Food Tech' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'govtech', label: 'GovTech' },
  { value: 'hardware', label: 'Hardware' },
  { value: 'healthtech', label: 'HealthTech' },
  { value: 'hr', label: 'HR Tech' },
  { value: 'insurtech', label: 'InsurTech' },
  { value: 'legaltech', label: 'LegalTech' },
  { value: 'logistics', label: 'Logistics / Supply Chain' },
  { value: 'marketplace', label: 'Marketplace' },
  { value: 'media', label: 'Media / Entertainment' },
  { value: 'proptech', label: 'PropTech / Real Estate' },
  { value: 'retail', label: 'Retail / E-commerce' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'saas', label: 'SaaS' },
  { value: 'space', label: 'SpaceTech' },
  { value: 'transportation', label: 'Transportation / Mobility' },
] as const

export const DEPARTMENTS = [
  { value: 'engineering', label: 'Engineering' },
  { value: 'product', label: 'Product' },
  { value: 'design', label: 'Design' },
  { value: 'data', label: 'Data / Analytics' },
  { value: 'sales', label: 'Sales' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'finance', label: 'Finance' },
  { value: 'hr', label: 'HR / People' },
  { value: 'operations', label: 'Operations' },
  { value: 'legal', label: 'Legal' },
  { value: 'customer_success', label: 'Customer Success' },
  { value: 'support', label: 'Support' },
  { value: 'other', label: 'Other' },
] as const

export const OUTREACH_TYPES = [
  { value: 'COLD_EMAIL', label: 'Cold Email' },
  { value: 'LINKEDIN_MESSAGE', label: 'LinkedIn Message' },
  { value: 'FOLLOW_UP', label: 'Follow-up Email' },
  { value: 'INTRODUCTION_REQUEST', label: 'Intro Request' },
] as const

export const OUTREACH_STATUSES = [
  { value: 'DRAFT', label: 'Draft' },
  { value: 'SENT', label: 'Sent' },
  { value: 'RESPONDED', label: 'Responded' },
  { value: 'NO_RESPONSE', label: 'No Response' },
  { value: 'ARCHIVED', label: 'Archived' },
] as const

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest First' },
  { value: 'oldest', label: 'Oldest First' },
  { value: 'amount_desc', label: 'Largest Amount' },
  { value: 'amount_asc', label: 'Smallest Amount' },
] as const
